Gestion/Controllers/DetalleController.cs
using Microsoft.AspNetCore.Mvc;

using Gestion.Datos;
using Gestion.Models;

namespace Gestion.Controllers
{
    public class DetalleController : Controller
    {
        DetalleDatos _detalleDatos = new DetalleDatos();

        public IActionResult Listar(int idFactura)
        {
            //La vista mostrará una lista  de Detalle de la Factura actual 
            var oLista = _detalleDatos.Listar(idFactura);

            return View(oLista);
        }

      
        public IActionResult Guardar()
        {
            //Metodo solo Devuelve la vista
            return View();

        }

        [HttpPost]
        public IActionResult Guardar(DetalleModel oDetalle)
        {

            //Metodo recibe el objeto para guardalo en bd 
            if (!ModelState.IsValid)
                return View();

            var respuesta = _detalleDatos.Guardar(oDetalle);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

        [HttpPost]      //metodo para modificar el objeto recibido  
        public IActionResult Editar(DetalleModel oDetalle)
        {
            if (!ModelState.IsValid)
                return View();
            var respuesta = _detalleDatos.Editar(oDetalle);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();

        }


        //metodo para recibir el objeto 
        public IActionResult Eliminar(int IdDetalle)
        {
            //Metodo solo devuelve la vista
            var oDetalle = _detalleDatos.Listar(IdDetalle);
            return View(oDetalle);

        }


        [HttpPost]      //metodo para modificar el objeto recibido  
        public IActionResult Eliminar(DetalleModel oDetalle)
        {

            var respuesta = _detalleDatos.Eliminar(oDetalle.IdDetalle);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();

        }
    }
}

Gestion/Controllers/FacturaController.cs
using Microsoft.AspNetCore.Mvc;

using Gestion.Datos;
using Gestion.Models;

namespace Gestion.Controllers
{
    public class FacturaController : Controller
    {
        FacturaDatos _facturaDatos = new FacturaDatos();

        public IActionResult Listar()
        {
            //La vista mostrará una lista deFacturas
            var oLista = _facturaDatos.Listar();


            return View(oLista);
        }

        //Recibir nombre deFactura 
        public IActionResult Consulta(int idfactura)
        {
            //Metodo solo devuelve la vista
            var olista = _facturaDatos.ConsultaFactura(idfactura);
            return View(olista);

        }

        public IActionResult Guardar()
        {
            //Metodo solo Devuelve la vista
            return View();

        }

        [HttpPost]
        public IActionResult Guardar(FacturaModel ofactura)
        {

            //Metodo recibe el objeto para guardalo en bd 
            if (!ModelState.IsValid)
                return View();

            var respuesta = _facturaDatos.Guardar(ofactura);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

        //metodo para recibir el objeto 
        public IActionResult Editar(int IdFactura)
        {
            //Metodo solo devuelve la vista
            var ofactura = _facturaDatos.Obtener(IdFactura);
            return View(ofactura);

        }


        [HttpPost]      //metodo para modificar el objeto recibido  
        public IActionResult Editar(FacturaModel ofactura)
        {
            if (!ModelState.IsValid)
                return View();
            var respuesta = _facturaDatos.Editar(ofactura);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();

        }


        //metodo para recibir el objeto 
        public IActionResult Eliminar(int IdFactura)
        {
            //Metodo solo devuelve la vista
            var ofactura = _facturaDatos.Obtener(IdFactura);
            return View(ofactura);

        }


        [HttpPost]      //metodo para modificar el objeto recibido  
        public IActionResult Eliminar(FacturaModel ofactura)
        {

            var respuesta = _facturaDatos.Eliminar(ofactura.IdFactura);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();

        }
    }
}

Gestion/Views/Factura/AnadirDetalle.cshtml
@model List<DetalleModel>
@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-left">
    <h1 class="display-1">@ViewData["Title"]</h1>
    <p>Detalle</p>
</div>

<br />
<br />


<div class="card">
    <div class="card-header">
        Añadir en la factura
        <a class="btn btn-success"><i class="bi bi-pencil-fill"></i>+</a>
        <!-- <a asp-action="Guardar" asp-controller="Detalle" class="btn btn-success"><i class="bi bi-pencil-fill"></i>+</a> -->
        <hr />
        <a><a asp-action="Editar" asp-controller="Detalle" a class="dropdown-item">Alterar Detalle</a></a>
    </div>
    <div class="card-body">
        <table class="table table-bordered">
            <thead>
                <tr>
                         <th>Nº de Factura</th>
                         <th>Concepto</th>
                         <th>Unidades</th>
                         <th>Precio</th>
                         <th>Importe</th> 
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {

                    <tr>
                        <td>@item.IdFactura</td>
                        <td>@item.Concepto</td>
                        <td>@item.Unidades</td>
                        <td>@item.Precio</td>
                        <td>@item.Importe</td>
           

                        <td>
                            <a asp-action="Editar" asp-controller="Detalle" class="btn btn-primary btn-sm" asp-route-IdCliente="@item.IdFactura"><i class="bi bi-pencil-fill"></i>Editar</a>

                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <hr />



    </div>
</div>

Gestion/Views/Factura/Editar.cshtml
@model FacturaModel

@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="card">
    <div class="card-header">
        Factura
    </div>
    <div class="card-body">

         
        <form asp-action="Editar" asp-controller="Factura" method="post">
            <input asp-for="IdFactura" type="hidden" class="form-control">

            <div class="mb-3">
                <label class="form-label">Cliente</label>
                <input asp-for="IdCliente" type="text" class="form-control">
                <span asp-validation-for="IdCliente" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Fecha</label>
                <input asp-for="Fecha" type="date" class="form-control">
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
                      
           <br>

            <button type="submit" class="btn btn-primary">Editar</button>
            <a asp-action="Listar" asp-controller="Factura" class="btn btn-warning">Cancelar</a>
        </form>

    </div>
</div>

Gestion/Views/Factura/Guardar.cshtml
@model FacturaModel

@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="card">
    <div class="card-header">
        Factura
    </div>
    <div class="card-body">


        <form asp-action="Editar" asp-controller="Factura" method="post">
            <input asp-for="IdFactura" type="hidden" class="form-control">

            <div class="mb-3">
                <label class="form-label">Cliente</label>
                <input asp-for="IdCliente" type="text" class="form-control">
                <span asp-validation-for="IdCliente" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Fecha</label>
                <input asp-for="Fecha" type="date" class="form-control">
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>

            <br>

            <button type="submit" class="btn btn-primary">Guardar</button>
            <a asp-action="Listar" asp-controller="Factura" class="btn btn-warning">Cancelar</a>
        </form>

    </div>
</div>

Gestion/Views/Factura/Listar.cshtml
@model List<FacturaModel>
@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-left">
    <h1 class="display-1">@ViewData["Title"]</h1>
    <p>Mantenimiento de Facturas</p>
</div>

<br />
<br />


<div class="card">
    <div class="card-header">
       Nueva Factura
       
       <a asp-action="Guardar" asp-controller="Factura" class="btn btn-success"><i class="bi bi-pencil-fill"></i>+</a> 
        <hr />
        <a><a asp-action="Editar" asp-controller="Factura" a class="dropdown-item">Alterar Factura</a></a>
    </div>
    <div class="card-body">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Nº de Factura</th>
                    <th>Cliente</th>
                    <th>Fecha</th>
               <!-- <th>Concepto</th>
                    <th>Unidades</th>
                    <th>Precio</th>
                    <th>Importe</th> -->                    
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {

                    <tr>
                        <td>@item.IdFactura</td>
                        <td>@item.IdCliente </td>
                        <td>@item.Fecha</td>
                        <!-- <th>Concepto</th>
                        <th>Unidades</th>
                        <th>Precio</th>
                        <th>Importe</th> -->

                        <td>
                            <a asp-action="Editar" asp-controller="Factura" class="btn btn-primary btn-sm" asp-route-IdFactura="@item.IdFactura"><i class="bi bi-pencil-fill"></i>Editar</a>
                            <a asp-action="AnadirDetalle" asp-controller="Factura" class="btn btn-primary btn-sm" asp-route-IdFactura="@item.IdFactura"><i class="bi bi-pencil-fill"></i>Añadir</a>

                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <hr />



    </div>
</div>