Gestion/Controllers/FacturaController.cs
using Microsoft.AspNetCore.Mvc;

using Gestion.Datos;
using Gestion.Models;

namespace Gestion.Controllers
{
    public class FacturaController : Controller
    {
        FacturaDatos _facturaDatos = new FacturaDatos();

        public IActionResult Listar()
        {
            //La vista mostrará una lista deFacturas
            var oLista = _facturaDatos.Listar();


            return View(oLista);
        }

        //Recibir nombre deFactura 
        public IActionResult Consulta(int idfactura)
        {
            //Metodo solo devuelve la vista
            var olista = _facturaDatos.ConsultaFactura(idfactura);
            return View(olista);

        }

        public IActionResult Guardar()
        {
            //Metodo solo Devuelve la vista
            return View();

        }

        [HttpPost]
        public IActionResult Guardar(FacturaModel ofactura)
        {

            //Metodo recibe el objeto para guardalo en bd 
            if (!ModelState.IsValid)
                return View();

            var respuesta = _facturaDatos.Guardar(ofactura);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

        //metodo para recibir el objeto 
        public IActionResult Editar(int IdFactura)
        {
            //Metodo solo devuelve la vista
            var ofactura = _facturaDatos.Obtener(IdFactura);
            return View(ofactura);

        }


        [HttpPost]      //metodo para modificar el objeto recibido  
        public IActionResult Editar(FacturaModel ofactura)
        {
            if (!ModelState.IsValid)
                return View();
            var respuesta = _facturaDatos.Editar(ofactura);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();

        }


        //metodo para recibir el objeto 
        public IActionResult Eliminar(int IdFactura)
        {
            //Metodo solo devuelve la vista
            var ofactura = _facturaDatos.Obtener(IdFactura);
            return View(ofactura);

        }


        [HttpPost]      //metodo para modificar el objeto recibido  
        public IActionResult Eliminar(FacturaModel ofactura)
        {

            var respuesta = _facturaDatos.Eliminar(ofactura.IdFactura);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();

        }
    }
}

Gestion/Controllers/HomeController.cs
using Gestion.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Gestion.Controllers
{
    public class HomeController : Controller
    {       

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Cliente()
        {
            return View();
        }

        public IActionResult Menu()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Gestion/Controllers/MantenedorController.cs
using Microsoft.AspNetCore.Mvc;

using Gestion.Datos;
using Gestion.Models;

namespace Gestion.Controllers
{
    public class MantenedorController : Controller
    {
        ClienteDatos _clienteDatos = new ClienteDatos(); 

        public IActionResult Listar()
        {
            //La vista mostrará una lista de Clientes
            var oLista = _clienteDatos.Listar(); 


            return View(oLista);
        }

      
        public IActionResult Guardar()
        {
            //Metodo solo Devuelve la vista
            return View();

        }

        [HttpPost]
        public IActionResult Guardar(ClienteModel oCliente)
        {

            //Metodo recibe el objeto para guardalo en bd 
            if (!ModelState.IsValid)
                return View();

            var respuesta = _clienteDatos.Guardar(oCliente);

            if (respuesta)
                return RedirectToAction("Listar");
            else 
                return View();
        }

        //metodo para recibir el objeto 
        public IActionResult Editar(int IdCliente)
        {
            //Metodo solo devuelve la vista
            var oCliente = _clienteDatos.Obtener(IdCliente);
            return View(oCliente);

        }


        [HttpPost]      //metodo para modificar el objeto recibido  
        public IActionResult Editar(ClienteModel ocliente)
        {
           if(!ModelState.IsValid)
                return View();
            var respuesta = _clienteDatos.Editar(ocliente);

            if (respuesta)
                return RedirectToAction("Listar");
            else 
                return View();

        }

        
        //metodo para recibir el objeto 
        public IActionResult Eliminar(int IdCliente)
        {
            //Metodo solo devuelve la vista
            var oCliente = _clienteDatos.Obtener(IdCliente);
            return View(oCliente);

        }


        [HttpPost]      //metodo para modificar el objeto recibido  
        public IActionResult Eliminar(ClienteModel ocliente)
        {
           
            var respuesta = _clienteDatos.Eliminar(ocliente.IdCliente);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();

        }
    }
}

Gestion/Views/Home/Cliente.cshtml
@{
    ViewData["Title"] = "Cliente";
}

<div class="text-left">
    <h1 class="display-1">@ViewData["Title"]</h1>
    <p>Mantenimiento de Clientes</p>
</div>


<div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label">nombre</label>
    <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
</div>
<div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label">Email address</label>
    <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
</div>
<div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label">Email address</label>
    <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
</div>
<div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label">Email address</label>
    <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
</div>

Gestion/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Factura</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Gestion/Views/Home/Menu.cshtml
@{
    ViewData["Title"] = "Menu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="vertical-menu">
    <a><a asp-action="Editar" asp-controller="Mantenedor" a class="dropdown-item">Cliente</a></a>
    <a><a asp-action="Listar" asp-controller="Mantenedor" a class="dropdown-item">Listado de Cliente </a></a>   
    <a><a asp-action="Listar" asp-controller="Factura" a class="dropdown-item">Lista Facturas</a></a>
   
   
</div>